baseURL = "https://zinzy.website"
languageCode = "en-us"
title = "Zinzy's website"
theme = "butterchicken"
[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:day/:slug/'
    notes = '/:slug/'
    pages = '/:slug'
  [permalinks.section]
    posts = '/posts/'