name: update all submodules
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Update module
        run: |
          git submodule update --init --recursive --checkout -f --remote
          git config --global user.name "Zinzy Waleson Geene"
          git config --global user.email "zinzy@pm.me"
          git commit -am "deployed"
          git push